import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import chalk from "chalk";
import { prompt, confirm, section, success, warn, error, info } from "./lib/display.js";

const CONFIG_DIR = path.join(os.homedir(), ".config", "fixd");
const CONFIG_PATH = path.join(CONFIG_DIR, ".env");

interface ConfigKey {
    key: string;
    description: string;
    required: boolean;
}

const CONFIG_KEYS: ConfigKey[] = [
    { key: "GROQ_API_KEY", description: "Groq API key (small/fast model — Llama 4 Scout)", required: true },
    { key: "OPENROUTER_API_KEY", description: "OpenRouter API key (large/smart model — primary)", required: false },
    { key: "CLARIFAI_PAT", description: "Clarifai PAT (large model fallback)", required: false },
    { key: "CONTEXT7_API_KEY", description: "Context7 API key (live library docs — optional)", required: false },
    { key: "FIXD_AUTO_RUN_LEVEL", description: "Auto-run level: conservative | moderate | aggressive (default: moderate)", required: false },
    { key: "FIXD_COMMAND_TIMEOUT", description: "Command timeout in ms (default: 120000)", required: false },
    { key: "OPENROUTER_LARGE_MODEL", description: "Override large model name on OpenRouter", required: false },
    { key: "SMALL_MODEL", description: "Override small model name on Groq", required: false },
];

function readCurrentConfig(): Record<string, string> {
    const config: Record<string, string> = {};
    if (!fs.existsSync(CONFIG_PATH)) return config;

    const lines = fs.readFileSync(CONFIG_PATH, "utf-8").split("\n");
    for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith("#")) continue;
        const eqIndex = trimmed.indexOf("=");
        if (eqIndex === -1) continue;
        const key = trimmed.slice(0, eqIndex).trim();
        const value = trimmed.slice(eqIndex + 1).trim();
        config[key] = value;
    }
    return config;
}

function writeConfig(config: Record<string, string>): void {
    fs.mkdirSync(CONFIG_DIR, { recursive: true });
    const lines = [
        "# fixd configuration",
        "# Generated by: fixd config",
        `# Updated: ${new Date().toISOString()}`,
        "",
    ];

    for (const [key, value] of Object.entries(config)) {
        if (value) lines.push(`${key}=${value}`);
    }

    fs.writeFileSync(CONFIG_PATH, `${lines.join("\n")}\n`, "utf-8");
}

function maskValue(value: string): string {
    if (!value) return chalk.red("not set");
    if (value.length <= 8) return chalk.yellow("***");
    return chalk.green(`${value.slice(0, 4)}****${value.slice(-4)}`);
}

async function validateGroqKey(key: string): Promise<boolean> {
    try {
        const res = await fetch("https://api.groq.com/openai/v1/models", {
            headers: { Authorization: `Bearer ${key}` },
            signal: AbortSignal.timeout(8000),
        });
        return res.ok;
    } catch {
        return false;
    }
}

async function validateOpenRouterKey(key: string): Promise<boolean> {
    try {
        const res = await fetch("https://openrouter.ai/api/v1/models", {
            headers: { Authorization: `Bearer ${key}` },
            signal: AbortSignal.timeout(8000),
        });
        return res.ok;
    } catch {
        return false;
    }
}

export async function runConfigWizard(): Promise<void> {
    section("fixd config");
    info(`Config file: ${CONFIG_PATH}`);
    console.log();

    const current = readCurrentConfig();

    console.log(chalk.bold("Current configuration:"));
    for (const { key, description, required } of CONFIG_KEYS) {
        const val = current[key] || process.env[key] || "";
        const status = val
            ? chalk.green("✓")
            : required
                ? chalk.red("✗ REQUIRED")
                : chalk.dim("○ optional");
        console.log(`  ${status}  ${chalk.cyan(key)}`);
        console.log(`       ${chalk.dim(description)}`);
        if (val) console.log(`       ${maskValue(val)}`);
        console.log();
    }

    const doWizard = await confirm("Run setup wizard to update keys?");
    if (!doWizard) return;

    console.log();
    const updated: Record<string, string> = { ...current };

    for (const { key, description, required } of CONFIG_KEYS) {
        const existing = current[key] || "";
        const hint = existing ? ` (current: ${maskValue(existing)}, press Enter to keep)` : "";
        const label = required ? chalk.red(`[required] ${key}`) : chalk.cyan(`[optional] ${key}`);

        console.log(`\n${label}`);
        console.log(chalk.dim(`  ${description}${hint}`));

        const value = await prompt("→");

        if (value.trim() === "" && existing) {
            updated[key] = existing;
            continue;
        }

        if (value.trim() === "" && !required) {
            continue;
        }

        if (value.trim() === "" && required) {
            warn(`${key} is required. Skipping for now — set it before using fixd doctor.`);
            continue;
        }

        updated[key] = value.trim();

        if (key === "GROQ_API_KEY" && updated[key]) {
            info("Validating Groq API key...");
            const valid = await validateGroqKey(updated[key]);
            valid
                ? success("Groq API key valid ✓")
                : warn("Could not validate Groq key (network issue or invalid). Saving anyway.");
        }

        if (key === "OPENROUTER_API_KEY" && updated[key]) {
            info("Validating OpenRouter API key...");
            const valid = await validateOpenRouterKey(updated[key]);
            valid
                ? success("OpenRouter API key valid ✓")
                : warn("Could not validate OpenRouter key. Saving anyway.");
        }
    }

    writeConfig(updated);
    console.log();
    success(`Configuration saved to ${CONFIG_PATH}`);
    info("Keys are loaded automatically on next fixd run.");
}

export function runConfigSet(keyval: string): void {
    const eqIndex = keyval.indexOf("=");
    if (eqIndex === -1) {
        error("Usage: fixd config set KEY=VALUE");
        process.exit(1);
    }

    const key = keyval.slice(0, eqIndex).trim().toUpperCase();
    const value = keyval.slice(eqIndex + 1).trim();

    const current = readCurrentConfig();
    current[key] = value;
    writeConfig(current);
    success(`Set ${key} in ${CONFIG_PATH}`);
}

export function runConfigGet(key: string): void {
    const upperKey = key.toUpperCase();
    const current = readCurrentConfig();
    const value = current[upperKey] || process.env[upperKey] || "";
    if (!value) {
        warn(`${upperKey} is not set`);
        return;
    }
    console.log(maskValue(value));
}

export function runConfigList(): void {
    section("fixd config");
    info(`Config file: ${CONFIG_PATH}`);
    console.log();

    const current = readCurrentConfig();

    for (const { key, required } of CONFIG_KEYS) {
        const val = current[key] || process.env[key] || "";
        const status = val
            ? chalk.green("✓")
            : required
                ? chalk.red("✗")
                : chalk.dim("○");
        console.log(`${status} ${chalk.cyan(key.padEnd(30))} ${val ? maskValue(val) : chalk.dim("not set")}`);
    }
}

export function runConfigDelete(key: string): void {
    const current = readCurrentConfig();
    const upperKey = key.toUpperCase();
    if (!(upperKey in current)) {
        warn(`${upperKey} not found in config`);
        return;
    }

    delete current[upperKey];
    writeConfig(current);
    success(`Deleted ${upperKey} from config`);
}
